name: Design By Tammy-Jade
favicon: null
layout_spectrum: 0.2791038188152015
typography_spectrum: 0.32157089258544147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8706700967159122
  lightness: 0.20553475595079362
  saturation: 0.7765010946895927
  rhythmicContrast: 0.1578660977538675
purpose: []
